### ISSUE TITLE
火狐的兼容性问题

### ISSUE THREAD

**Issue by wxmup** [Redlnn/lemon-new-tab-page#12]
首先感谢开发者大大的开发,我很喜欢这个起始页.

现在有个问题,火狐的'新标签页',和'主页和新窗口'是分开的.而开发者大大的拓展,只是修改了新标签页,
火狐的逻辑是,第一次打开火狐,显示的是主页和新窗口(没有办法修改成显示新标签页).这意味着还需手动启动新标签页,才会启动柠檬起始页.

**Comment by Redlnn** [comment]
已支持，已提交审核，估计很快就更新了，谢谢支持~
