### ISSUE TITLE
置顶网站仍然没有图标

### ISSUE THREAD

**Issue by wxmup** [Redlnn/lemon-new-tab-page#14]
![图片](https://github.com/user-attachments/assets/43bfe478-424a-4974-a824-2327694c0312)

**Comment by Redlnn** [comment]
置顶的图标需要在添加的时候关闭这个按钮手动选择图片哦
![image](https://github.com/user-attachments/assets/8c17ca31-7f9f-43b3-97e8-29ced9f43b67)

最常访问没有图标是 Chromium 的问题，你可以屏蔽这个链接或者添加一个链接相同的置顶并手动选择图标

我这边测试了png、svg、ico图标都正常哦

![image](https://github.com/user-attachments/assets/904a97e6-9dfc-4a17-82d9-a8aa85608e56)

**Comment by wxmup** [comment]
> 置顶的图标需要在添加的时候关闭这个按钮手动选择图片哦 ![image](https://private-user-images.githubusercontent.com/41742767/376115157-8c17ca31-7f9f-43b3-97e8-29ced9f43b67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NzcwMDIsIm5iZiI6MTcyODk3NjcwMiwicGF0aCI6Ii80MTc0Mjc2Ny8zNzYxMTUxNTctOGMxN2NhMzEtN2Y5Zi00M2IzLTk3ZTgtMjljZWQ5ZjQzYjY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDA3MTgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjYjg5NDhhNzU1MjkxMTM4YzY3MWZjMGZiNDkzYjZiODViOWVhN2MwMWMwYWQyN2VmODE2MTE4N2IyMTk4ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8dJ4vz0Bw9TYpHN0IdTqO30TDzWfgcwRhoziQrZ4ZuY)
> 
> 最常访问没有图标是 Chromium 的问题，你可以屏蔽这个链接或者添加一个链接相同的置顶并手动选择图标
> 
> 我这边测试了png、svg、ico图标都正常哦
> 
> ![image](https://private-user-images.githubusercontent.com/41742767/376115546-904a97e6-9dfc-4a17-82d9-a8aa85608e56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NzcwMDIsIm5iZiI6MTcyODk3NjcwMiwicGF0aCI6Ii80MTc0Mjc2Ny8zNzYxMTU1NDYtOTA0YTk3ZTYtOWRmYy00YTE3LTgyZDktYThhYTg1NjA4ZTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDA3MTgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0OWUzMmUwMzJjYWNjMTQyYjBjZjJmODUyYmE5ZWM2ZWUxZDJhNTliNDgxOTFjYzhjYzllNWJjNTgwMjQzYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vkd9KjNKA06dRv6l1IUjf5qAWqc5OqdwfF3hYk5j3_4)

ok.了解了。🙏
