### ISSUE TITLE
最常访问有些删除不了

### ISSUE THREAD

**Issue by weikangqi** [Redlnn/lemon-new-tab-page#8]
有些网站可以删除，有些删除不了，但是会显示已移除快捷方式

**Comment by Redlnn** [comment]
> 有些网站可以删除，有些删除不了，但是会显示已移除快捷方式

有没有更详细的复现步骤呢

**Comment by weikangqi** [comment]
可以给下邮箱，或者QQ联系方式嘛，我可以录一段视频给你

**Comment by Redlnn** [comment]
> 可以给下邮箱，或者QQ联系方式嘛，我可以录一段视频给你，我的邮箱是[tomqii996@gmail.com](mailto:tomqii996@gmail.com)

已发邮件
